server:
  port: 7777
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
    username: 'sa'
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2
    open-in-view: false
  h2:
    console:
      enabled: true
      path: '/h2'
  mustache:
    suffix: .html
  devtools:
    livereload:
      enabled: true